### ISSUE TITLE
Error when build to apk

### ISSUE THREAD

**Issue by muhtarudinsiregar** [brenopolanski/aiEyes#14]
Hi, i get error when build to apk
this the error message
```
[INFO] Running app-scripts build: --prod --platform android --target cordova

[14:27:31]  build prod started ...
[14:27:31]  clean started ...
[14:27:31]  clean finished in 41 ms
[14:27:31]  copy started ...
[14:27:31]  ngc started ...
[14:27:46]  ngc finished in 14.81 s
[14:27:46]  preprocess started ...
[14:27:46]  deeplinks started ...
[14:27:46]  deeplinks finished in 317 ms
[14:27:46]  optimization started ...
[14:27:47]  copy finished in 16.18 s
[14:27:59]  optimization finished in 12.74 s
[14:27:59]  preprocess finished in 13.07 s
[14:27:59]  webpack started ...
[14:28:07]  webpack finished in 8.87 s
[14:28:07]  sass started ...
[14:28:08]  uglifyjs started ...
Error: Uglify failed: Unexpected token: name (ImageDetailPage) in undefined at line undefined, col undefined, pos undefined
    at BuildError.Error (native)
    at new BuildError (D:\LEARNING\IONIC\aiEyes\node_modules\@ionic\app-scripts\dist\util\errors.js:16:28)
    at taskReject (D:\LEARNING\IONIC\aiEyes\node_modules\@ionic\app-scripts\dist\worker-process.js:36:22)
    at D:\LEARNING\IONIC\aiEyes\node_modules\@ionic\app-scripts\dist\worker-process.js:14:13
[14:28:09]  sass finished in 1.59 s
[14:28:09]  cleancss started ...
[14:28:11]  cleancss finished in 1.50 s
```

ionic info
```
$ ionic info

cli packages: (C:\Users\root\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.13.0
    ionic (Ionic CLI) : 3.13.0

global packages:

    cordova (Cordova CLI) : 7.1.0

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 26.0.2
    Node              : v6.11.3
    npm               : 3.10.10
    OS                : Windows 10

Misc:

    backend : legacy

```

**Comment by brenopolanski** [comment]
@muhtarudinsiregar  did you try run the app on your phone?

https://github.com/brenopolanski/aiEyes#run-the-app-on-your-phone

**Comment by muhtarudinsiregar** [comment]
yes, i want to run in my phone but i want to build to apk.

updated: 
 i can build with `ionic cordova build android ` without --prod.

thank you for your reply 😃

**Comment by brenopolanski** [comment]
No problems @muhtarudinsiregar :)
